version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: whizkidefos/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=whizkidefos
      - PG_PASSWORD=123456
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=whizkidefos
      - POSTGRES_PASSWORD=123456
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}